"""Generate schema

Revision ID: 8f501cface72
Revises: 
Create Date: 2021-12-20 02:50:10.249963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f501cface72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.alter_column('locations', 'x',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'y',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_stats', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('player_stats', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('players', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'players', ['stats_id'])
    op.create_foreign_key(None, 'players', 'locations', ['location_x'], ['x'])
    op.create_foreign_key(None, 'players', 'locations', ['location_y'], ['y'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='unique')
    op.alter_column('players', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('player_stats', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('player_stats', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('locations', 'y',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locations', 'x',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
